name: Build Hackage packages

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  batch-1-of-2:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build nix/non-broken-haskell-packages.nix -A non-broken.${{ inputs.package }}
