name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      # Make nix-shell use specific Bash version.
      # Cf. https://nixos.org/manual/nix/stable/command-ref/nix-shell#environment-variables.
      - name: Set shell Bash
        run: echo "NIX_BUILD_SHELL=$(nix-build -A pkgs.bash nix/pkgs.nix)/bin/bash" >> $GITHUB_ENV
      - run: nix-shell --run 'test/test.sh'
