name: Build Hackage packages

on:
  push:
  pull_request:

jobs:
  nix-build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nix_file: [nix/non-broken-haskell-packages.nix]
        package: [yesod-session-persist, yesod-sitemap, yesod-static, yesod-table, yesod-tableview, yesod-test, yesod-websockets, yesod-websockets-extra, yet-another-logger, yi-gtk, yi-rope, yi-vty, yices-easy, yices-painless, yiyd, yjsvg, yjtools, yocto, yoga, youtube, yst, yu-auth, yu-utils, yx, z3, zalgo, zcache, zenacy-html, zenacy-unicode, zenc, zenhack-prelude, zeromq4-haskell, zeromq4-simple, zigzag, zim-parser, zinza, zip, zip-archive, zip-cmd, zip-stream, zippers, zlib, zlib-bindings, zlib-clib, zlib-conduit, zmidi-core, zot, zre, zstd, ztar, zxcvbn-c, zxcvbn-hs]
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-build -f ${{ matrix.nix_file }} -A ${{ matrix.package }}
